using System.Collections.Generic;

public static class GameDataHolder {

    public static Dictionary<string, string> Data = new Dictionary<string, string>() {
        { "Localization\\English", "{  \"StatWeight\": \"Weight: {0}\",  \"StatCakes\": \"Cakes: {0}\",  \"StatTeas\": \"Teas: {0}\",  \"MenuStart\": \"PLAY\",  \"MenuResume\": \"RESUME\",  \"MenuControls\": \"CONTROLS\",  \"MenuLanguage\": \"LANGUAGE\",  \"MenuExit\": \"EXIT\",  \"ControlsMovement\": \"Move\",  \"ControlsJumping\": \"Jump\",  \"ControlsPickup\": \"Pickup\",  \"ControlsResetLevel\": \"Retry\",  \"ControlsMenu\": \"Main Menu\",  \"TipWelcome\": \"Welcome !!! Eat them all !\",  \"TipUseCheckpointReset\": \"Hit 'R' if you get stuck !\",  \"TipFirstCakeConsumedNomNom\": \"Nom nom nom, YUMMY !!!\",  \"TipFirstCakeConsumedMaximizeWeight\": \"Eat more cakes, you'll feel better.\",  \"TipReachedMaxWeightPressButtons\": \"You've put on some pounds, You are able to press buttons now !\",  \"TipReachedMaxWeightPickupItem\": \"Try to pick up an item with 'E'.\",  \"TipFirstTeaConsumedResetWeight\": \"Wow ! Looking gooood. The tea resets your weight !\",  \"TipFirstTeaConsumeFitCorridors\": \"You can fit through narrow corridors now.\",  \"TipFirstTeaConsumeJumpHigh\": \"And jump high once again.\",  \"TipHopedOnButtonNotEnoughWeight\": \"You need to to maximize your weight to press buttons.\",  \"TipHopedOnButtonEnoughWeight\": \"Good job. Something Happened !\",  \"TipHopedOnButtonEnoughWeightNoItem\": \"Did you know that you can trigger buttons with items ?\"}"},
        { "Localization\\French", "{  \"StatWeight\": \"Weight: {0}\",  \"StatCakes\": \"Cakes: {0}\",  \"StatTeas\": \"Teas: {0}\",  \"MenuStart\": \"PLAY\",  \"MenuResume\": \"RESUME\",  \"MenuControls\": \"CONTROLS\",  \"MenuLanguage\": \"LANGUAGE\",  \"MenuExit\": \"EXIT\",  \"ControlsMovement\": \"Move\",  \"ControlsJumping\": \"Jump\",  \"ControlsPickup\": \"Pickup\",  \"ControlsResetLevel\": \"Retry\",  \"ControlsMenu\": \"Main Menu\",  \"TipWelcome\": \"Welcome !!! Eat them all !\",  \"TipUseCheckpointReset\": \"Hit 'R' if you get stuck !\",  \"TipFirstCakeConsumedNomNom\": \"Nom nom nom, YUMMY !!!\",  \"TipFirstCakeConsumedMaximizeWeight\": \"Eat more cakes, you'll feel better.\",  \"TipReachedMaxWeightPressButtons\": \"You've put on some pounds, You are able to press buttons now !\",  \"TipReachedMaxWeightPickupItem\": \"Try to pick up an item with 'E'.\",  \"TipFirstTeaConsumedResetWeight\": \"Wow ! Looking gooood. The tea resets your weight !\",  \"TipFirstTeaConsumeFitCorridors\": \"You can fit through narrow corridors now.\",  \"TipFirstTeaConsumeJumpHigh\": \"And jump high once again.\",  \"TipHopedOnButtonNotEnoughWeight\": \"You need to to maximize your weight to press buttons.\",  \"TipHopedOnButtonEnoughWeight\": \"Good job. Something Happened !\",  \"TipHopedOnButtonEnoughWeightNoItem\": \"Did you know that you can trigger buttons with items ?\"}"},
        { "Localization\\Greek", "{  \"StatWeight\": \"Βάρος: {0}\",  \"StatCakes\": \"Τούρτες: {0}\",  \"StatTeas\": \"Τσάι: {0}\",  \"MenuStart\": \"ΠΑΜΕ\",  \"MenuResume\": \"ΠΑΜΕ\",  \"MenuControls\": \"ΚΟΥΜΠΙΑ\",  \"MenuLanguage\": \"ΓΛΩΣΣΑ\",  \"MenuExit\": \"ΕΞΩ\",  \"ControlsMovement\": \"Κούνα\",  \"ControlsJumping\": \"Πήδα\",  \"ControlsPickup\": \"Πάρε\",  \"ControlsResetLevel\": \"Κύκλους\",  \"ControlsMenu\": \"Ποζ\",  \"TipWelcome\": \"Γεία σου κόκλα !!! Τσίμπα τα τουρτάκια !\",  \"TipUseCheckpointReset\": \"Πατα 'R' αν κολλήσεις !\",  \"TipFirstCakeConsumedNomNom\": \"Πο πο πο, ΚΟΛΑΣΗ !!!\",  \"TipFirstCakeConsumedMaximizeWeight\": \"Φάε κιάλλο θα νιώσεις καλύτερα.\",  \"TipReachedMaxWeightPressButtons\": \"Σαν να πήρες κανα κιλάκι, Μπορείς να πατήσεις κουμπιά τωρα !\",  \"TipReachedMaxWeightPickupItem\": \"Δοκίμασε να σηκώσεις αντικείμενα με το 'E'.\",  \"TipFirstTeaConsumedResetWeight\": \"Ουάου ! Γίναμε μοντελακι. Το τσάι σε φέρνει στα ίσα σου !\",  \"TipFirstTeaConsumeFitCorridors\": \"Τώρα χωράς απο στενούς διαδρόμους.\",  \"TipFirstTeaConsumeJumpHigh\": \"Και μπορείς να πηδήξεις ψηλα ξανά.\",  \"TipHopedOnButtonNotEnoughWeight\": \"Πρέπει να τελικιάσεις το βάρος σου για να πατήσεις κουμπιά.\",  \"TipHopedOnButtonEnoughWeight\": \"Μπράβο. Το κουμπι ενεργοποιήθηκε !\",  \"TipHopedOnButtonEnoughWeightNoItem\": \"Το ξέρεις οτι μπορείς να ενεργοποιήσεις κουμπια με το αντικείμενα ;\"}"}
    };

}
