using System.Collections.Generic;

public static class GameDataHolder {

    public static Dictionary<string, string> Data = new Dictionary<string, string>() {
        { "Localization/Chinese", "{  \"StatWeight\": \"重量: {0}\",  \"StatCakes\": \"蛋糕: {0}\",  \"StatTeas\": \"茶: {0}\",  \"MenuStart\": \"玩\",  \"MenuResume\": \"恢复\",  \"MenuControls\": \"控制\",  \"MenuLanguage\": \"语言\",  \"MenuExit\": \"出口\",  \"ControlsMovement\": \"移动\",  \"ControlsJumping\": \"跳\",  \"ControlsPickup\": \"捡起\",  \"ControlsResetLevel\": \"重试\",  \"ControlsMenu\": \"主菜单\",  \"TipWelcome\": \"欢迎！全部吃\",  \"TipUseCheckpointReset\": \"如果卡住了，打“R”\",  \"TipFirstCakeConsumedNomNom\": \"Nom nom nom, YUMMY !!!\",  \"TipFirstCakeConsumedMaximizeWeight\": \"吃更多的蛋糕，你会感觉更好\",  \"TipReachedMaxWeightPressButtons\": \"你已经穿上了一些磅，你现在可以按下按钮\",  \"TipReachedMaxWeightPickupItem\": \"尝试用“E”选取一个项目。\",  \"TipFirstTeaConsumedResetWeight\": \"哇 ！看起来不错。茶重新设置你的体重\",  \"TipFirstTeaConsumeFitCorridors\": \"你现在可以穿过狭窄的走廊。\",  \"TipFirstTeaConsumeJumpHigh\": \"又一次跳高\",  \"TipHopedOnButtonNotEnoughWeight\": \"你需要最大化你的体重来按下按钮\",  \"TipHopedOnButtonEnoughWeight\": \"做得好。发生了一些事 \",  \"TipHopedOnButtonEnoughWeightNoItem\": \"你知道你可以用物品触发按钮吗\"}"},
        { "Localization/English", "{  \"StatWeight\": \"Weight: {0}\",  \"StatCakes\": \"Cakes: {0}\",  \"StatTeas\": \"Teas: {0}\",  \"MenuStart\": \"PLAY\",  \"MenuResume\": \"RESUME\",  \"MenuControls\": \"CONTROLS\",  \"MenuLanguage\": \"LANGUAGE\",  \"MenuExit\": \"EXIT\",  \"ControlsMovement\": \"Move\",  \"ControlsJumping\": \"Jump\",  \"ControlsPickup\": \"Pickup\",  \"ControlsResetLevel\": \"Retry\",  \"ControlsMenu\": \"Main Menu\",  \"TipWelcome\": \"Welcome !!! Eat them all !\",  \"TipUseCheckpointReset\": \"Hit 'R' if you get stuck !\",  \"TipFirstCakeConsumedNomNom\": \"Nom nom nom, YUMMY !!!\",  \"TipFirstCakeConsumedMaximizeWeight\": \"Eat more cakes, you'll feel better.\",  \"TipReachedMaxWeightPressButtons\": \"You've put on some pounds, You are able to press buttons now !\",  \"TipReachedMaxWeightPickupItem\": \"Try to pick up an item with 'E'.\",  \"TipFirstTeaConsumedResetWeight\": \"Wow ! Looking gooood. The tea resets your weight !\",  \"TipFirstTeaConsumeFitCorridors\": \"You can fit through narrow corridors now.\",  \"TipFirstTeaConsumeJumpHigh\": \"And jump high once again.\",  \"TipHopedOnButtonNotEnoughWeight\": \"You need to to maximize your weight to press buttons.\",  \"TipHopedOnButtonEnoughWeight\": \"Good job. Something Happened !\",  \"TipHopedOnButtonEnoughWeightNoItem\": \"Did you know that you can trigger buttons with items ?\"}"},
        { "Localization/French", "{  \"StatWeight\": \"Weight: {0}\",  \"StatCakes\": \"Cakes: {0}\",  \"StatTeas\": \"Teas: {0}\",  \"MenuStart\": \"PLAY\",  \"MenuResume\": \"RESUME\",  \"MenuControls\": \"CONTROLS\",  \"MenuLanguage\": \"LANGUAGE\",  \"MenuExit\": \"EXIT\",  \"ControlsMovement\": \"Move\",  \"ControlsJumping\": \"Jump\",  \"ControlsPickup\": \"Pickup\",  \"ControlsResetLevel\": \"Retry\",  \"ControlsMenu\": \"Main Menu\",  \"TipWelcome\": \"Welcome !!! Eat them all !\",  \"TipUseCheckpointReset\": \"Hit 'R' if you get stuck !\",  \"TipFirstCakeConsumedNomNom\": \"Nom nom nom, YUMMY !!!\",  \"TipFirstCakeConsumedMaximizeWeight\": \"Eat more cakes, you'll feel better.\",  \"TipReachedMaxWeightPressButtons\": \"You've put on some pounds, You are able to press buttons now !\",  \"TipReachedMaxWeightPickupItem\": \"Try to pick up an item with 'E'.\",  \"TipFirstTeaConsumedResetWeight\": \"Wow ! Looking gooood. The tea resets your weight !\",  \"TipFirstTeaConsumeFitCorridors\": \"You can fit through narrow corridors now.\",  \"TipFirstTeaConsumeJumpHigh\": \"And jump high once again.\",  \"TipHopedOnButtonNotEnoughWeight\": \"You need to to maximize your weight to press buttons.\",  \"TipHopedOnButtonEnoughWeight\": \"Good job. Something Happened !\",  \"TipHopedOnButtonEnoughWeightNoItem\": \"Did you know that you can trigger buttons with items ?\"}"},
        { "Localization/Greek", "{  \"StatWeight\": \"Βάρος: {0}\",  \"StatCakes\": \"Τούρτες: {0}\",  \"StatTeas\": \"Τσάι: {0}\",  \"MenuStart\": \"ΠΑΜΕ\",  \"MenuResume\": \"ΠΑΜΕ\",  \"MenuControls\": \"ΚΟΥΜΠΙΑ\",  \"MenuLanguage\": \"ΓΛΩΣΣΑ\",  \"MenuExit\": \"ΕΞΩ\",  \"ControlsMovement\": \"Πέρα δώθε\",  \"ControlsJumping\": \"Πήδα\",  \"ControlsPickup\": \"Σήκωσε\",  \"ControlsResetLevel\": \"Κύκλους\",  \"ControlsMenu\": \"Ποζ\",  \"TipWelcome\": \"Γεία σου κόκλα !!! Τσίμπα τα τουρτάκια !\",  \"TipUseCheckpointReset\": \"Πατα 'R' αν κολλήσεις !\",  \"TipFirstCakeConsumedNomNom\": \"Πο πο πο, ΚΟΛΑΣΗ !!!\",  \"TipFirstCakeConsumedMaximizeWeight\": \"Φάε κιάλλο θα νιώσεις καλύτερα.\",  \"TipReachedMaxWeightPressButtons\": \"Σαν να πήρες κανα κιλάκι, Μπορείς να πατήσεις κουμπιά τωρα !\",  \"TipReachedMaxWeightPickupItem\": \"Δοκίμασε να σηκώσεις αντικείμενα με το 'E'.\",  \"TipFirstTeaConsumedResetWeight\": \"Ουάου ! Γίναμε μοντελακι. Το τσάι σε φέρνει στα ίσα σου !\",  \"TipFirstTeaConsumeFitCorridors\": \"Τώρα χωράς απο στενούς διαδρόμους.\",  \"TipFirstTeaConsumeJumpHigh\": \"Και μπορείς να πηδήξεις ψηλα ξανά.\",  \"TipHopedOnButtonNotEnoughWeight\": \"Πρέπει να τελικιάσεις το βάρος σου για να πατήσεις κουμπιά.\",  \"TipHopedOnButtonEnoughWeight\": \"Μπράβο. Το κουμπι ενεργοποιήθηκε !\",  \"TipHopedOnButtonEnoughWeightNoItem\": \"Το ξέρεις οτι μπορείς να ενεργοποιήσεις κουμπια με αντικείμενα ;\"}"}
    };

}
